# Generated by Django 5.1.3 on 2025-09-23 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_proposal_catatan_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivitas', models.TextField()),
                ('jenis', models.TextField()),
                ('lingkup', models.TextField()),
                ('kuantitas', models.IntegerField()),
                ('poin', models.IntegerField()),
                ('keterangan', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='aktivitas/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelanggaran', models.TextField()),
                ('lingkup', models.TextField()),
                ('kuantitas', models.IntegerField()),
                ('poin', models.IntegerField()),
                ('keterangan', models.TextField()),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggaran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
