# Generated by Django 5.1.3 on 2025-09-23 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_aktivitas_pelanggaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelanggaran', models.TextField()),
                ('lingkup', models.TextField()),
                ('poin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidang', models.TextField()),
                ('aktivitas', models.TextField()),
                ('jenis', models.TextField()),
                ('lingkup', models.TextField()),
                ('poin', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aktivitas',
            name='aktivitas',
        ),
        migrations.RemoveField(
            model_name='aktivitas',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='aktivitas',
            name='lingkup',
        ),
        migrations.RemoveField(
            model_name='aktivitas',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='aktivitas',
            name='poin',
        ),
        migrations.RemoveField(
            model_name='pelanggaran',
            name='lingkup',
        ),
        migrations.RemoveField(
            model_name='pelanggaran',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='pelanggaran',
            name='pelanggaran',
        ),
        migrations.RemoveField(
            model_name='pelanggaran',
            name='poin',
        ),
        migrations.AddField(
            model_name='aktivitas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aktivitas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelanggaran_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aktivitas',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitas',
            name='kuantitas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='kuantitas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='aturan_demerit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='contacts.demerit'),
        ),
        migrations.AddField(
            model_name='aktivitas',
            name='aturan_merit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='contacts.merit'),
        ),
    ]
