# Generated by Django 5.1.3 on 2025-10-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_demerit_merit_remove_aktivitas_aktivitas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitas',
            name='aktivitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_detail', to='contacts.merit'),
        ),
        migrations.AddField(
            model_name='aktivitas',
            name='jenis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jenis_detail', to='contacts.merit'),
        ),
        migrations.AddField(
            model_name='aktivitas',
            name='lingkup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lingkup_detail', to='contacts.merit'),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='lingkup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lingkup_detail', to='contacts.demerit'),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='pelanggaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelanggaran_detail', to='contacts.demerit'),
        ),
    ]
