# Generated by Django 5.1.3 on 2025-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_aktivitas_aktivitas_aktivitas_jenis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merit',
            name='lingkup',
            field=models.TextField(choices=[('internal', 'Internal'), ('eksternal', 'Eksternal')], default='internal', max_length=25),
        ),
    ]
