# Generated by Django 5.1.3 on 2025-10-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_alter_merit_lingkup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitas',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demerit',
            name='lingkup',
            field=models.TextField(choices=[('internal', 'Internal'), ('eksternal', 'Eksternal')], default='internal', max_length=25),
        ),
    ]
