# Generated by Django 5.1.3 on 2025-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_alter_aktivitas_file_alter_demerit_lingkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='angkatan',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nim',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prodi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
