# Generated by Django 5.1.3 on 2025-10-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_user_angkatan_user_nim_user_prodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modal_poin',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='nim',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
