# Generated by Django 5.1.3 on 2025-10-31 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_user_modal_poin_alter_user_nim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angkatan', models.CharField(blank=True, max_length=4, null=True)),
                ('modal_poin', models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='user',
            name='angkatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_angkatan', to='contacts.angkatan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modal_poin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modal_poin_user', to='contacts.angkatan'),
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
