# Generated by Django 5.1.3 on 2025-10-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_angkatan_delete_contact_alter_user_angkatan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modal_poin',
        ),
        migrations.AlterField(
            model_name='user',
            name='angkatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='contacts.angkatan'),
        ),
    ]
